module.exports = {
  User: require("./User"),
  History: require("./History"),
  GuestUser: require("./GuestUser"),
  Chat: require("./Chat"),
  ModelFeedback: require("./ModelFeedback"),
  Reminder: require("./Reminder"),
  Plant: require("./Plant"),
  Post: require("./Post"),
  Comment: require("./Comment"),
  TreatmentPlan: require("./TreatmentPlan"),
  Recommendation: require("./Recommendation"),
  TwoFactorCode: require("./TwoFactorCode"),
  Subscription: require("./Subscription"),
  Notification: require("./Notification"),
  Contact: require("./Contact"),
  AuditLog: require("./AuditLog"),
  Analytics: require("./Analytics"),
};
